<a href="https://colab.research.google.com/github/duaneywadey/colab/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def factorialNum(num):
  factorial = 1  
  for i in range(1, num+1):
    factorial = factorial * i
  return factorial


  

print(factorialNum(5))

120


In [ ]:
import numpy as np


In [ ]:
from time import process_time

In [ ]:
from time import process_time

python_list = [i for i in range(1000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0002207870000017209


In [ ]:
import numpy as np

np_array = np.array([i for i in range(10000)])

start_time = process_time()

In [ ]:
np_array += 5 

end_time = process_time()

print(end_time - start_time)

1.0033876159999977


In [ ]:
import numpy as np

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 

end_time = process_time()

print(end_time - start_time)

0.00039019700000153534


In [ ]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4), (5,6,7,8)]) 

In [ ]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
print(c)
type(c) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


numpy.ndarray

In [ ]:
c.shape


(3, 4)

In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)], dtype=float)
print(c)
type(c)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


numpy.ndarray

In [ ]:
import numpy as np

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:

y = np.zeros((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z = np.full((5,4),8)
print(z)


[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
f = np.random.random((3,4))
print(f)



[[0.43309458 0.41298297 0.26192689 0.31540944]
 [0.03175884 0.38306853 0.36235041 0.00765891]
 [0.04100892 0.98431478 0.82318002 0.8066759 ]]


In [ ]:
import random
g = np.random.randint(10,1000,(3,5))
print(g)


[[252 988 922 549 352]
 [ 39  54 862 284 244]
 [270 626 748 986 595]]


In [ ]:
import random
import numpy as np

g = np.random.randint(10,10000,(3,5))
print(g)

[[4309 4489 5044 2826  396]
 [2905 6141 8955 2756 5048]
 [7292 1264 7964 8958 9890]]


In [ ]:
print(g)

[[4309 4489 5044 2826  396]
 [2905 6141 8955 2756 5048]
 [7292 1264 7964 8958 9890]]


In [ ]:
for x in range(1,5):
  print(g)

[[4309 4489 5044 2826  396]
 [2905 6141 8955 2756 5048]
 [7292 1264 7964 8958 9890]]
[[4309 4489 5044 2826  396]
 [2905 6141 8955 2756 5048]
 [7292 1264 7964 8958 9890]]
[[4309 4489 5044 2826  396]
 [2905 6141 8955 2756 5048]
 [7292 1264 7964 8958 9890]]
[[4309 4489 5044 2826  396]
 [2905 6141 8955 2756 5048]
 [7292 1264 7964 8958 9890]]


In [ ]:
for x in range(1,5):
  g = np.random.randint(10,10000,(3,5))
  print(g)
  

[[1929 3547 1401 4197 1233]
 [6760 1201 5252 2547 4885]
 [4332 3607 9704 7843 7019]]
[[3150 8863 6404 1995 4077]
 [9638  356 4410 8509 5022]
 [9049 2847 4603 9710 8814]]
[[3498 5338 9083 6048 2324]
 [8064 7804 2814 6641 9072]
 [1087 9809 1927 4395 1160]]
[[4870 9773 5865 4100 3697]
 [ 861  756 3430 4174 1730]
 [ 346  235  353 2627 4826]]


In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
print(c)
type(c) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


numpy.ndarray

In [ ]:
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
d = np.arange(10,40,8)
print(d)

[10 18 26 34]


In [ ]:
#Convert an array to numpy array

list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)


[10 20 20 20 50]


numpy.ndarray

In [ ]:
c = np.random.randint(10,90,(10,3))
print(c)

[[38 28 81]
 [21 43 30]
 [35 61 88]
 [38 66 21]
 [79 33 14]
 [14 22 53]
 [31 34 50]
 [75 46 36]
 [14 46 29]
 [41 53 21]]


In [ ]:
#10 rows, 3 columns
print(c.shape)


(10, 3)


In [ ]:
#Dimensions
print(c.ndim)

2


In [ ]:
#Number of elements in an array
print(c.size)

30


In [ ]:
#Check the data type of the values in an array
print(c.dtype)

int64


In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
np_array = np.asarray(list2)
print(np_array)

[ 6  7  8  9 10]


In [ ]:
list3 = list1 + list2
np_array = np.asarray(list3)
print(np_array)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.random.randint(0,10,(4,5))
b = np.random.randint(10,20,(4,5))
print(a)
print(b)

[[1 5 0 4 8]
 [9 2 0 8 8]
 [3 6 7 1 1]
 [3 7 6 6 2]]
[[16 15 15 11 17]
 [17 14 16 15 12]
 [12 17 18 10 15]
 [10 12 12 15 19]]


In [ ]:
a = np.random.randint(0,10,(4,5))
b = np.random.randint(10,20,(4,5))

print(a+b)
print(a-b)
print(a/b)
print(a*b)

[[23 22 22 22 16]
 [19 11 19 21 15]
 [18 23 15 25 17]
 [20 22 19 17 17]]
[[-13 -12  -8  -4  -8]
 [-13 -11 -11 -13 -15]
 [-12 -11 -11 -11  -3]
 [ -6 -10 -15  -7  -5]]
[[0.27777778 0.29411765 0.46666667 0.69230769 0.33333333]
 [0.1875     0.         0.26666667 0.23529412 0.        ]
 [0.2        0.35294118 0.15384615 0.38888889 0.7       ]
 [0.53846154 0.375      0.11764706 0.41666667 0.54545455]]
[[ 90  85 105 117  48]
 [ 48   0  60  68   0]
 [ 45 102  26 126  70]
 [ 91  96  34  60  66]]


In [ ]:
print(a)
print(b)

[[5 5 7 9 4]
 [3 0 4 4 0]
 [3 6 2 7 7]
 [7 6 2 5 6]]
[[18 17 15 13 12]
 [16 11 15 17 15]
 [15 17 13 18 10]
 [13 16 17 12 11]]


In [ ]:
print(a)
print(b)

print("ADDITION")
print(np.add(a,b))
print("SUBSTRACTION")
print(np.subtract(a,b))
print("MULTIPLICATION")
print(np.multiply(a,b))

[[5 5 7 9 4]
 [3 0 4 4 0]
 [3 6 2 7 7]
 [7 6 2 5 6]]
[[18 17 15 13 12]
 [16 11 15 17 15]
 [15 17 13 18 10]
 [13 16 17 12 11]]
ADDITION
[[23 22 22 22 16]
 [19 11 19 21 15]
 [18 23 15 25 17]
 [20 22 19 17 17]]
SUBSTRACTION
[[-13 -12  -8  -4  -8]
 [-13 -11 -11 -13 -15]
 [-12 -11 -11 -11  -3]
 [ -6 -10 -15  -7  -5]]
MULTIPLICATION
[[ 90  85 105 117  48]
 [ 48   0  60  68   0]
 [ 45 102  26 126  70]
 [ 91  96  34  60  66]]


In [ ]:
array = np.random.randint(1,10,(3,5))
print(array)

[[9 3 1 2 4]
 [9 7 2 9 3]
 [4 1 4 7 4]]


In [ ]:
print(array.shape)

(3, 5)


In [ ]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 9 4]
 [3 7 1]
 [1 2 4]
 [2 9 7]
 [4 3 4]]
(5, 3)


In [ ]:
import numpy as np

In [ ]:
array = np.random.randint(1,10,(3,5))
print(array)

[[5 7 6 2 2]
 [1 6 6 1 2]
 [9 5 4 1 8]]


In [ ]:
array = np.random.randint(100,1000, (5,7))
print(array)

[[505 357 191 312 887 597 982]
 [843 123 854 697 454 469 209]
 [157 511 502 458 507 697 239]
 [413 217 553 203 567 228 848]
 [932 342 953 763 743 649 134]]
